application:
  title:  Microservicios de Productos
  version: 1.0.0
  author: Diego Rodriguez

server:
  port: 8081
  servlet:
    context-path: /ms-productos/v1/


# Postgres #
spring: 
  datasource:
    url:  jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: diego123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
  main:
    allow-bean-definition-overriding: true
